---
arch_packages:
  - 1password
  - bitwarden
  - discord
  - docker
  - docker-buildx
  - docker-compose
  - firefox
  - flatpak
  - ghostty
  - google-chrome
  - libvirt
  - mattermost-desktop
  - openssh
  - quickemu-git
  - rustup
  - spotify
  - thunderbird
  - virt-manager
  - visual-studio-code-bin
  - zed