---
- name: Local provisioning for this machine
  hosts: localhost
  connection: local
  become: false
  gather_facts: yes

  vars: {}

  tasks:
    - name: Stat authorized_keys
      ansible.builtin.stat:
        path: "{{ lookup('env','HOME') }}/.ssh/authorized_keys"
      register: ssh_keys_stat

    - name: Import SSH keys via tasks file when authorized_keys is missing
      include_tasks: tasks/create_authorized_keys.yml
      when: not ssh_keys_stat.stat.exists

    - name: Create Firefox profile 'dominik' if profiles.ini does not exist
      include_tasks: tasks/create_firefox_profile.yml

    - name: Create Thunderbird profile
      include_tasks: tasks/create_thunderbird_profile.yml

    - name: Create btrfs subvolumes for /nix and /var/lib/docker if on btrfs filesystem
      include_tasks: tasks/create_btrfs_subvolumes.yml

    - name: Determine distribution key from gathered facts
      set_fact:
        distribution: "{{ ansible_facts['distribution'] | default('unknown') | lower | replace(' ', '_') }}"

    - name: Load distribution-specific package lists if present
      include_vars:
        file: "{{ playbook_dir }}/distributions/{{ distribution }}/packages.yml"

    - name: Include distribution-specific tasks when present
      include_tasks: "{{ playbook_dir }}/distributions/{{ distribution }}/main.yml"

    - name: Ensure openssh server is enabled and started
      ansible.builtin.systemd:
        name: sshd
        enabled: true
        state: started
      become: true

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: libvirt
        append: yes
      become: true
